### ISSUE TITLE
Where is the spyc_load_file function defined?

### ISSUE THREAD

**Issue by ppazos** [Philipp15b/php-i18n#66]
```
Fatal error: Uncaught Error: Call to undefined function i18n\spyc_load_file() in /home/pablo/GitHub/trauma-emr-proto/i18n/I18n.php:302 

Stack trace: 
#0 /home/pablo/GitHub/trauma-emr-proto/i18n/I18n.php(149): i18n\I18n->load('/home/pablo/Git...') 
#1 /home/pablo/GitHub/trauma-emr-proto/index.php(139): i18n\I18n->init() 
#2 {main} thrown in /home/pablo/GitHub/trauma-emr-proto/i18n/I18n.php on line 302
```

**Comment by ppazos** [comment]
Found this library but it is not handling the yaml examples on this project correctly, has errors with parent: child nodes.

https://github.com/mustangostang/spyc

**Comment by Philipp15b** [comment]
Oh, it's assumed you use composer to install the library, which will automatically install the `spyc` dependency. But apparently that's not documented 😅, so I'll mark this as a bug. Happy to accept a PR to add some documentation.
